export const notNullFields = ['handoff_timestamp'];

export function titleize(fieldName: string) {
  const word = fieldName.replace(/_/g, ' ');
  const wordsArray = word.split(' ');
  const capitalizedArray = wordsArray.map(e => {
    return e.charAt(0).toUpperCase() + e.slice(1).toLowerCase();
  });
  return capitalizedArray.join(' ');
}

export const databaseFieldsNameMap = {
  fam_num: 'Spouse Name',
  unhcr_case_file_family_adultminor_2: 'Kimlik Number',
  unhcr_case_file_family_adultminor_6: 'External Services Info Received',
  ar_full_name: 'AR Full Name',
  en_full_name: 'EN Full Name',
  email_address1: 'Email Address 1',
  unhcr_number: 'UNHCR Number',
  usrap_case_number: 'USRAP Case Number',
  lgbt: 'LGBT',
  icorn_cpj: 'ICORN CPJ',
  siv: 'SIV',
  siv_1059: 'SIV 1059',
  siv_101a: 'SIV 101a',
  siv_follow_to_join: 'SIV Follow to Join',
  us_prior_admission: 'US Prior Admission',
  usrap_access: 'USRAP Access',
  dap_via_i_130: 'DAP via I 130',
  dap_via_ev: 'DAP via EV',
  dap_as_relative_of_siv: 'DAP as Relative of SIV',
  rfr_submission: 'RFR Submission',
  eo_waiver: 'EO Waiver',
  createdAt: 'Created At',
};

export const databaseFields = [
  'age',
  'arcurrentcountry',
  'arfullrsc',
  'arnationality1',
  'arrsc',
  'ar_full_name',
  'blocked',
  'canadian_private_sponsorhip',
  'canadian_sponsorship_info_rating',
  'canadian_sponsorship_info_response',
  'child_illness',
  'createdAt',
  'created_on',
  'current_country',
  'dapev_info_rating',
  'dapev_info_response',
  'dapi130_info_rating',
  'dapi130_info_response',
  'daprelsiv_info_rating',
  'daprelsiv_response',
  'dap_via_i_130',
  'dap_via_ev',
  'dap_as_relative_of_siv',
  'email_address1',
  'end_feedback_follow_up_conversation',
  'end_feedback_helpfulness_open_ended',
  'end_feedback_helpfulness_rating',
  'end_feedback_other_information_needs',
  'end_feedback_recommend_open_ended',
  'end_feedback_recommend_rating',
  'en_full_name',
  'eo_waiver',
  'fam_num',
  'firstname',
  'fullrsc',
  'gender',
  'germany_family_reunification',
  'german_reunification_info_rating',
  'german_reunification_info_response',
  'groups',
  'handoff_timestamp',
  'has_unhcr_file',
  'hired_lawyer',
  'i_130_f',
  'i130_info_rating',
  'i130_info_response',
  'i_130_ir',
  'i730_info_rating',
  'i730_info_response',
  'i_730_pathway',
  'icorn_cpj',
  'icorn_info_rating',
  'icorn_info_response',
  'id',
  'lack_of_durable_solutions',
  'language',
  'lgbt',
  'lppn_score',
  'marital_status',
  'medical_needs_score',
  'minor_or_adult',
  'modified_on',
  'name',
  'nationality1',
  'nationality2',
  'nationality3',
  'ongoing_usrap',
  'p_3',
  'p3_info_rating',
  'p3_info_response',
  'pause_handoffs',
  'phone_number',
  'prescreening_complete',
  'previous_us_resettlement',
  'pro_se_guidance_received',
  'referral_complete',
  'relative_abroad_location',
  'relative_abroad_location1',
  'relative_abroad_location3',
  'relative_abroad_location4',
  'relative_abroad_location5',
  'relative_abroad_name',
  'relative_abroad_name1',
  'relative_abroad_name2',
  'resettlement_relatives',
  'rfr_submission',
  'rsc',
  'rsc_case_status_portal',
  'rsc_contact_email',
  'siv',
  'siv_follow_to_join',
  'siv_101a',
  'siv_1059',
  'stopped',
  'svt',
  'textitContactName',
  'textitContactUuid',
  'textitSessionId',
  'unaccompanied_minor',
  'unhcr_case_file_family_adultminor_2',
  'unhcr_case_file_family_adultminor_6',
  'unhcr_number',
  'unique_session_id',
  'updatedAt',
  'urns',
  'us_relative_relationship',
  'us_relative_relationship1',
  'us_prior_admission',
  'usrap_access',
  'usrap_case_number',
  'usrap_info_rating',
  'usrap_info_response',
  'uuid',
  'vulnerability_assessed',
  'western_left',
  'western_right',
  'women_and_girls_at_risk',
];
