export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_REDIRECTING = 'SIGNUP_REDIRECTING';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REDIRECTING = 'LOGIN_REDIRECTING';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const EXPORTING_IRAP_DATA = 'EXPORT_IRAP_DATA';
export const EXPORT_IRAP_DATA_SUCCESS = 'EXPORT_IRAP_DATA_SUCCESS';
export const EXPORT_IRAP_DATA_FAILURE = 'EXPORT_IRAP_DATA_FAILURE';

export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_FAILURE = 'FETCH_ORGANIZATIONS_FAILURE';
